[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "blockOpInf"
version = "0.1.0"
authors = [{name = "Benjamin Zastrow", email = "ben.g.zastrow@gmail.com"}]
description = "Block-structured operator inference ROMs for aerostructural applications."